name: dotprompt_dart
description: A Dart package for parsing .prompt files for use with LLMs.
version: 0.4.0
repository: https://github.com/csells/dotprompt_dart

environment:
  sdk: ^3.7.2

dependencies:
  collection: ^1.19.1
  json_schema: ^5.2.1
  mustache_template: ^2.0.0
  path: ^1.8.0
  yaml: ^3.1.2

dev_dependencies:
  all_lint_rules_community: ^0.0.43
  test: ^1.24.0
